import Head from "next/head";
import { HorizontalCard, VerticalCard } from "@/component/card";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main>
        <HorizontalCard size={500} />
        <div className="grid grid-flow-col">
          <VerticalCard size={250} />
          <VerticalCard size={250} />
          <VerticalCard size={250} />
        </div>
      </main>
    </>
  );
}
