import { AuthShowcase } from "@/component/buttons";
import Head from "next/head";

const UsersInfo = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <AuthShowcase />
        </div>
      </main>
    </>
  );
};
export default UsersInfo;
